[package]
name = "chip8-emulator-in-rust"
version = "0.1.0"
authors = ["Francisco de Souza Júnior <francisco.junior@luizalabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]