name: Build

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - name: clean
        run: cargo clean
      - name: build
        run: cargo build --verbose
        env:
          RUST_BACKTRACE: 1
      - name: test
        run: cargo test -- --test-threads 1
        env:
          RUST_BACKTRACE: 1
      - name: ignored test
        run: cargo test -- --test-threads 1 --ignored || true
        env:
          RUST_BACKTRACE: 1
        if: matrix.version == 'nightly'
      - name: check formatting
        run: cargo fmt -- --check